
var imgHost = "https://taroturana.oss-cn-shanghai.aliyuncs.com/";

var imgs = [
  "baojian1.png",
  "baojian2.png",
  "baojian3.png",
  "baojian4.png",
  "baojian5.png",
  "baojian6.png",
  "baojian7.png",
  "baojian8.png",
  "baojian9.png",
  "baojian10.png",
  "baojian_guowang.png",
  "baojian_huanghou.png",
  "baojian_qishi.png",
  "baojian_shiwei.png",
  "emo.png",
  "gaota.png",
  "huangdi.png",
  "jiaohuang.png",
  "jiezhi.png",
  "lianren.png",
  "liliang.png",
  "mingyunzhilun.png",
  "moshushi.png",
  "nvhuang.png",
  "nvjishi.png",
  "quanzhang1.png",
  "quanzhang2.png",
  "quanzhang3.png",
  "quanzhang4.png",
  "quanzhang5.png",
  "quanzhang6.png",
  "quanzhang7.png",
  "quanzhang8.png",
  "quanzhang9.png",
  "quanzhang10.png",
  "quanzhang_guowang.png",
  "quanzhang_huanghou.png",
  "quanzhang_qishi.png",
  "quanzhang_shiwei.png",
  "shenbei1.png",
  "shenbei10.png",
  "shenbei2.png",
  "shenbei3.png",
  "shenbei4.png",
  "shenbei5.png",
  "shenbei6.png",
  "shenbei7.png",
  "shenbei8.png",
  "shenbei9.png",
  "shenbei_guowang.png",
  "shenbei_huanghou.png",
  "shenbei_qishi.png",
  "shenbei_shiwei.png",
  "shenpan.png",
  "shijie.png",
  "sishen.png",
  "taiyang.png",
  "xingbi1.png",
  "xingbi10.png",
  "xingbi2.png",
  "xingbi3.png",
  "xingbi4.png",
  "xingbi5.png",
  "xingbi6.png",
  "xingbi7.png",
  "xingbi8.png",
  "xingbi9.png",
  "xingbi_guowang.png",
  "xingbi_huanghou.png",
  "xingbi_qishi.png",
  "xingbi_shiwei.png",
  "xing.png",   
  "xuandiaozhe.png",
  "yinshi.png",
  "yueliang.png",
  "yuren.png",
  "zhanche.png",
  "zhengyi.png",
]

module.exports = {
  imgHost: imgHost,
  imgs : imgs
}